package hu.bme.mit.inf.mvsd.futsal.core.database;

// Generated 2013.05.25. 20:05:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrewRole generated by hbm2java
 */
@Entity
@Table(name = "CrewRole", catalog = "futsaldb")
public class CrewRole implements java.io.Serializable {

	private int id;
	private String name;
	private String nameEn;
	private String nameHu;
	private Set<Crew> crews = new HashSet<Crew>(0);

	public CrewRole() {
	}

	public CrewRole(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public CrewRole(int id, String name, String nameEn, String nameHu,
			Set<Crew> crews) {
		this.id = id;
		this.name = name;
		this.nameEn = nameEn;
		this.nameHu = nameHu;
		this.crews = crews;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NameEN", length = 45)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "NameHU", length = 45)
	public String getNameHu() {
		return this.nameHu;
	}

	public void setNameHu(String nameHu) {
		this.nameHu = nameHu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Crew> getCrews() {
		return this.crews;
	}

	public void setCrews(Set<Crew> crews) {
		this.crews = crews;
	}

}
