package hu.bme.mit.inf.mvsd.futsal.core.database;

// Generated 2013.05.25. 20:05:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GoalKeeper generated by hbm2java
 */
@Entity
@Table(name = "GoalKeeper", catalog = "futsaldb")
public class GoalKeeper implements java.io.Serializable {

	private int id;
	private Team team;
	private Account account;
	private int licenseNumber;
	private Integer squadNumber;

	public GoalKeeper() {
	}

	public GoalKeeper(int id, Account account, int licenseNumber) {
		this.id = id;
		this.account = account;
		this.licenseNumber = licenseNumber;
	}

	public GoalKeeper(int id, Team team, Account account, int licenseNumber,
			Integer squadNumber) {
		this.id = id;
		this.team = team;
		this.account = account;
		this.licenseNumber = licenseNumber;
		this.squadNumber = squadNumber;
	}

	@Id
	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TeamId")
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccId", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "LicenseNumber", nullable = false)
	public int getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(int licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "SquadNumber")
	public Integer getSquadNumber() {
		return this.squadNumber;
	}

	public void setSquadNumber(Integer squadNumber) {
		this.squadNumber = squadNumber;
	}

}
