package hu.bme.mit.inf.mvsd.futsal.core.database;

// Generated 2013.05.25. 20:05:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pitch generated by hbm2java
 */
@Entity
@Table(name = "Pitch", catalog = "futsaldb")
public class Pitch implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;

	public Pitch() {
	}

	public Pitch(String name, String address) {
		this.name = name;
		this.address = address;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
