package hu.bme.mit.inf.mvsd.futsal.core.database;

// Generated 2013.05.25. 20:05:45 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Referee generated by hbm2java
 */
@Entity
@Table(name = "Referee", catalog = "futsaldb")
public class Referee implements java.io.Serializable {

	private int id;
	private Account account;
	private int identifier;

	public Referee() {
	}

	public Referee(int id, Account account, int identifier) {
		this.id = id;
		this.account = account;
		this.identifier = identifier;
	}

	@Id
	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccId", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Identifier", nullable = false)
	public int getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(int identifier) {
		this.identifier = identifier;
	}

}
