package hu.bme.mit.inf.mvsd.futsal.reportgeneration;

import com.google.common.base.Objects;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Crew;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.CrewRole;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Fault;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.FaultType;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Goal;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.GoalKeeper;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Match;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Pitch;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Player;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Referee;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Substitution;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Supervisor;
import hu.bme.mit.inf.mvsd.domain.generated.futsal.Team;
import hu.bme.mit.inf.mvsd.futsal.reportgeneration.GeneratorHelper;
import java.util.Date;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Exceptions;

@SuppressWarnings("all")
public class HtmlGenerator {
  public void generate(final Match match, final String path) {
    try {
      CharSequence _generateHtml = this.generateHtml(match);
      String _string = _generateHtml.toString();
      GeneratorHelper.writeHtmlFile(path, _string);
    } catch (Exception _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  public CharSequence generateHtml(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html>");
    _builder.newLine();
    CharSequence _generateHtmlHeader = this.generateHtmlHeader(match);
    _builder.append(_generateHtmlHeader, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateHtmlBody = this.generateHtmlBody(match);
    _builder.append(_generateHtmlBody, "");
    _builder.newLineIfNotEmpty();
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateHtmlHeader(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"cache-control\" content=\"no-cache\" />");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1250\" />");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"Content-Language\" content=\"hu\" />");
    _builder.newLine();
    _builder.append("<meta name=\"title\" content=\"Magyar Labdar\u00FAg\u00F3 Sz\u00F6vets\u00E9g Adatbank\" />");
    _builder.newLine();
    _builder.append("<meta name=\"description\" content=\"Magyar Labdar\u00FAg\u00F3 Sz\u00F6vets\u00E9g Adatbank\" />");
    _builder.newLine();
    _builder.append("<meta name=\"keywords\" content=\"mlsz foci labdar\u00FAg\u00E1s football adatbank\" />");
    _builder.newLine();
    _builder.append("<meta name=\"language\" content=\"magyar\" />");
    _builder.newLine();
    _builder.append("<!--meta name=\"copyright\" content=\"Copyright &copy; 2009 SZ\u00C1M\u00CDTHAT KFT\" /-->");
    _builder.newLine();
    _builder.append("<meta name=\"robots\" content=\"index, follow, all\" />");
    _builder.newLine();
    _builder.append("<meta name=\"distribution\" content=\"Global\" />");
    _builder.newLine();
    _builder.append("<meta name=\"revisit-after\" content=\"1 Week\" />");
    _builder.newLine();
    _builder.append("<meta name=\"rating\" content=\"General\" />");
    _builder.newLine();
    _builder.append("<meta name=\"doc-type\" content=\"Web Page\" />");
    _builder.newLine();
    _builder.append("<meta http-equiv=\"imagetoolbar\" content=\"no\" />");
    _builder.newLine();
    _builder.append("<meta name=\"verify-v1\" content=\"NbcFoFDQeCFhmcD57l4QmYh9w3z0nCGSetVfJgIUDnI=\" />");
    _builder.newLine();
    _builder.append("<title>Magyar Labdar\u00FAg\u00F3 Sz\u00F6vets\u00E9g adatbankja - MVSD</title>");
    _builder.newLine();
    _builder.append("<link rel=\"stylesheet\" href=\"http://adatbank.mlsz.hu/_include/include.css\" type=\"text/css\">");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\" src=\"http://adatbank.mlsz.hu/_include/util.js\"></script>");
    _builder.newLine();
    _builder.append("<script type=\"text/VBScript\" src=\"http://adatbank.mlsz.hu/_include/utilvb.js\"></script>");
    _builder.newLine();
    _builder.append("</head>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateHtmlBody(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<body topmargin=\"0\" leftmargin=\"0\" link=\"#000080\" vlink=\"#000080\" alink=\"#000080\" OnKeyDown=\"ProcessKeyDown();\">");
    _builder.newLine();
    _builder.append("<DIV id=overDiv style=\"Z-INDEX: 1000; VISIBILITY: hidden; POSITION: absolute\"></DIV>");
    _builder.newLine();
    _builder.append("<SCRIPT language=\"VBScript\">");
    _builder.newLine();
    _builder.append("function ProcessKeyDown()");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Dim WinEvent");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Set WinEvent = window.event");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("if WinEvent.keycode = 13 Then");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("WinEvent.keycode = 9");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("End if");
    _builder.newLine();
    _builder.append("End function");
    _builder.newLine();
    _builder.append("</SCRIPT>");
    _builder.newLine();
    _builder.append("<body topmargin=\"0\" leftmargin=\"0\" link=\"#000080\" vlink=\"#000080\" alink=\"#000080\" OnKeyDown=\"ProcessKeyDown();\" style=\"background: url(\'/images/hatter/bg_homok.jpg\') repeat-x;\">");
    _builder.newLine();
    _builder.append("<center>");
    _builder.newLine();
    CharSequence _generateTableHeader = this.generateTableHeader(match);
    _builder.append(_generateTableHeader, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateStarters = this.generateStarters(match);
    _builder.append(_generateStarters, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateSubstitutes = this.generateSubstitutes(match);
    _builder.append(_generateSubstitutes, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateBench = this.generateBench(match);
    _builder.append(_generateBench, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateScorers = this.generateScorers(match);
    _builder.append(_generateScorers, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateFaults = this.generateFaults(match);
    _builder.append(_generateFaults, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateSubstitutions = this.generateSubstitutions(match);
    _builder.append(_generateSubstitutions, "");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"740\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>             ");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</body>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateTableHeader(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" width=\"740\" height=\"600\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td valign=\"top\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEHER_BARNA_CL13\" width=\"360\" height=\"30\"><b>");
    String _chanmpionship = match.getChanmpionship();
    _builder.append(_chanmpionship, "      ");
    _builder.append("</b></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"FEHER_BARNA_CR13\" width=\"340\"><b>Magyar Labdar\u00FAg\u00F3 Sz\u00F6vets\u00E9g</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"10\"></td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_HATTER_1\" width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_HATTER_1_CL13\" width=\"220\" height=\"25\"><b>");
    Date _date = match.getDate();
    String _localeString = _date.toLocaleString();
    _builder.append(_localeString, "      ");
    _builder.append("</b></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_HATTER_1_CR13\" width=\"500\"><b>");
    Pitch _location = match.getLocation();
    String _address = _location.getAddress();
    _builder.append(_address, "      ");
    _builder.append(", ");
    Pitch _location_1 = match.getLocation();
    String _name = _location_1.getName();
    _builder.append(_name, "      ");
    _builder.append("</b></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_HATTER_1\" width=\"10\"></td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\"></td></tr>");
    _builder.newLine();
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>            ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CC14\" width=\"314\" height=\"36\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<b>");
    _builder.newLine();
    _builder.append("         ");
    Team _team1 = match.getTeam1();
    String _name_1 = _team1.getName();
    _builder.append(_name_1, "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</b>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>            ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" background=\"http://adatbank.mlsz.hu/images/hatter/eredmeny_72x36.jpg\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEHER_TRANSPARENT_CC18\" width=\"72\" height=\"21\"><b>");
    Team _team1_1 = match.getTeam1();
    int _calculateScore = GeneratorHelper.calculateScore(_team1_1, false);
    _builder.append(_calculateScore, "                     ");
    _builder.append(" - ");
    Team _team2 = match.getTeam2();
    int _calculateScore_1 = GeneratorHelper.calculateScore(_team2, false);
    _builder.append(_calculateScore_1, "                     ");
    _builder.append("</b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEHER_TRANSPARENT_CC11\" width=\"72\" height=\"14\"><b>");
    Team _team1_2 = match.getTeam1();
    int _calculateScore_2 = GeneratorHelper.calculateScore(_team1_2, true);
    _builder.append(_calculateScore_2, "                     ");
    _builder.append(" - ");
    Team _team2_1 = match.getTeam2();
    int _calculateScore_3 = GeneratorHelper.calculateScore(_team2_1, true);
    _builder.append(_calculateScore_3, "                     ");
    _builder.append("</b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append(" ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CC14\" width=\"314\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<b>");
    _builder.newLine();
    _builder.append("         ");
    Team _team2_2 = match.getTeam2();
    String _name_2 = _team2_2.getName();
    _builder.append(_name_2, "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</b>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>         ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_HATTER_1\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td>         ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"65\" height=\"20\">j\u00E1t\u00E9kvezet\u0151:</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekvezeto_nez_p01_jegyzokonyv_nez_1(\'");
    int _xifexpression = (int) 0;
    Referee _referee1 = match.getReferee1();
    boolean _equals = Objects.equal(_referee1, null);
    if (_equals) {
      _xifexpression = 0;
    } else {
      Referee _referee1_1 = match.getReferee1();
      int _identifier = _referee1_1.getIdentifier();
      _xifexpression = _identifier;
    }
    _builder.append(_xifexpression, "                  ");
    _builder.append("\');\">         ");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEKETE_TRANSPARENT_CL10\" width=\"165\"><b>");
    String _xifexpression_1 = null;
    boolean _or = false;
    Referee _referee1_2 = match.getReferee1();
    boolean _equals_1 = Objects.equal(_referee1_2, null);
    if (_equals_1) {
      _or = true;
    } else {
      Referee _referee1_3 = match.getReferee1();
      String _name_3 = _referee1_3.getName();
      boolean _equals_2 = Objects.equal(_name_3, null);
      _or = (_equals_1 || _equals_2);
    }
    if (_or) {
      _xifexpression_1 = "";
    } else {
      Referee _referee1_4 = match.getReferee1();
      String _name_4 = _referee1_4.getName();
      String _upperCase = _name_4.toUpperCase();
      _xifexpression_1 = _upperCase;
    }
    _builder.append(_xifexpression_1, "                     ");
    _builder.append(" </b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td> ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"65\">asszisztens:</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekvezeto_nez_p01_jegyzokonyv_nez_1(\'");
    int _xifexpression_2 = (int) 0;
    Referee _referee2 = match.getReferee2();
    boolean _equals_3 = Objects.equal(_referee2, null);
    if (_equals_3) {
      _xifexpression_2 = 0;
    } else {
      Referee _referee2_1 = match.getReferee2();
      int _identifier_1 = _referee2_1.getIdentifier();
      _xifexpression_2 = _identifier_1;
    }
    _builder.append(_xifexpression_2, "                  ");
    _builder.append("\');\">         ");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEKETE_TRANSPARENT_CL10\" width=\"165\"><b>");
    String _xifexpression_3 = null;
    boolean _or_1 = false;
    Referee _referee2_2 = match.getReferee2();
    boolean _equals_4 = Objects.equal(_referee2_2, null);
    if (_equals_4) {
      _or_1 = true;
    } else {
      Referee _referee2_3 = match.getReferee2();
      String _name_5 = _referee2_3.getName();
      boolean _equals_5 = Objects.equal(_name_5, null);
      _or_1 = (_equals_4 || _equals_5);
    }
    if (_or_1) {
      _xifexpression_3 = "";
    } else {
      Referee _referee2_4 = match.getReferee2();
      String _name_6 = _referee2_4.getName();
      String _upperCase_1 = _name_6.toUpperCase();
      _xifexpression_3 = _upperCase_1;
    }
    _builder.append(_xifexpression_3, "                     ");
    _builder.append(" </b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"65\">ellen\u0151r:</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\'; OnClick=\"jatekvezeto_nez_p01_jegyzokonyv_nez_1(\'");
    int _xifexpression_4 = (int) 0;
    Supervisor _supervisor = match.getSupervisor();
    boolean _equals_6 = Objects.equal(_supervisor, null);
    if (_equals_6) {
      _xifexpression_4 = 0;
    } else {
      Supervisor _supervisor_1 = match.getSupervisor();
      int _identifier_2 = _supervisor_1.getIdentifier();
      _xifexpression_4 = _identifier_2;
    }
    _builder.append(_xifexpression_4, "                  ");
    _builder.append("\');\">         ");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEKETE_TRANSPARENT_CL10\" width=\"165\"><b>");
    String _xifexpression_5 = null;
    boolean _or_2 = false;
    Supervisor _supervisor_2 = match.getSupervisor();
    boolean _equals_7 = Objects.equal(_supervisor_2, null);
    if (_equals_7) {
      _or_2 = true;
    } else {
      Supervisor _supervisor_3 = match.getSupervisor();
      String _name_7 = _supervisor_3.getName();
      boolean _equals_8 = Objects.equal(_name_7, null);
      _or_2 = (_equals_7 || _equals_8);
    }
    if (_or_2) {
      _xifexpression_5 = "";
    } else {
      Supervisor _supervisor_4 = match.getSupervisor();
      String _name_8 = _supervisor_4.getName();
      String _upperCase_2 = _name_8.toUpperCase();
      _xifexpression_5 = _upperCase_2;
    }
    _builder.append(_xifexpression_5, "                     ");
    _builder.append(" </b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td> ");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>         ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td> ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"65\" height=\"20\">tartjv.:</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\">         ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEKETE_TRANSPARENT_CL10\" width=\"165\"></td></tr>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td> ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"65\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekvezeto_nez_p01_jegyzokonyv_nez_1(\'");
    int _xifexpression_6 = (int) 0;
    Referee _referee3 = match.getReferee3();
    boolean _equals_9 = Objects.equal(_referee3, null);
    if (_equals_9) {
      _xifexpression_6 = 0;
    } else {
      Referee _referee3_1 = match.getReferee3();
      int _identifier_3 = _referee3_1.getIdentifier();
      _xifexpression_6 = _identifier_3;
    }
    _builder.append(_xifexpression_6, "                  ");
    _builder.append("\');\">         ");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("<tr><td class=\"FEKETE_TRANSPARENT_CL10\" width=\"165\"><b>");
    String _xifexpression_7 = null;
    boolean _or_3 = false;
    Referee _referee3_2 = match.getReferee3();
    boolean _equals_10 = Objects.equal(_referee3_2, null);
    if (_equals_10) {
      _or_3 = true;
    } else {
      Referee _referee3_3 = match.getReferee3();
      String _name_9 = _referee3_3.getName();
      boolean _equals_11 = Objects.equal(_name_9, null);
      _or_3 = (_equals_10 || _equals_11);
    }
    if (_or_3) {
      _xifexpression_7 = "";
    } else {
      Referee _referee3_4 = match.getReferee3();
      String _name_10 = _referee3_4.getName();
      String _upperCase_3 = _name_10.toUpperCase();
      _xifexpression_7 = _upperCase_3;
    }
    _builder.append(_xifexpression_7, "                     ");
    _builder.append(" </b></td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("                  ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"65\">sz\u00F6v.ell.:</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"165\">");
    _builder.newLine();
    _builder.append("                  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td> ");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>     ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>                      ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>         ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CR11\" width=\"50\" height=\"15\">fordul\u00F3</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>        ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL11\" width=\"120\">szak\u00E1g</td>                 ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL11\" width=\"157\">koroszt\u00E1ly</td>                 ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL11\" width=\"95\">t\u00EDpus</td> ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL11\" width=\"95\">\u00E9vad</td> ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CR11\" width=\"178\">m\u00E9rk\u0151z\u00E9s k\u00F3dja</td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CR14\" width=\"50\" height=\"20\"><b>");
    String _xifexpression_8 = null;
    int _round = match.getRound();
    boolean _equals_12 = Objects.equal(Integer.valueOf(_round), null);
    if (_equals_12) {
      _xifexpression_8 = "-";
    } else {
      int _round_1 = match.getRound();
      String _plus = (Integer.valueOf(_round_1) + ".");
      _xifexpression_8 = _plus;
    }
    _builder.append(_xifexpression_8, "               ");
    _builder.append("</b></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>        ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL12\" width=\"120\"><b>");
    String _xifexpression_9 = null;
    String _section = match.getSection();
    boolean _equals_13 = Objects.equal(_section, null);
    if (_equals_13) {
      _xifexpression_9 = "-";
    } else {
      String _section_1 = match.getSection();
      _xifexpression_9 = _section_1;
    }
    _builder.append(_xifexpression_9, "               ");
    _builder.append("</b></td>                 ");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL12\" width=\"157\"><b>");
    String _xifexpression_10 = null;
    String _ageGroup = match.getAgeGroup();
    boolean _equals_14 = Objects.equal(_ageGroup, null);
    if (_equals_14) {
      _xifexpression_10 = "-";
    } else {
      String _ageGroup_1 = match.getAgeGroup();
      _xifexpression_10 = _ageGroup_1;
    }
    _builder.append(_xifexpression_10, "               ");
    _builder.append("</b></td>                 ");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL12\" width=\"95\"><b>");
    String _xifexpression_11 = null;
    String _category = match.getCategory();
    boolean _equals_15 = Objects.equal(_category, null);
    if (_equals_15) {
      _xifexpression_11 = "-";
    } else {
      String _category_1 = match.getCategory();
      _xifexpression_11 = _category_1;
    }
    _builder.append(_xifexpression_11, "               ");
    _builder.append("</b></td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td width=\"4\"></td>    ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CL12\" width=\"95\"><b>");
    String _xifexpression_12 = null;
    String _season = match.getSeason();
    boolean _equals_16 = Objects.equal(_season, null);
    if (_equals_16) {
      _xifexpression_12 = "-";
    } else {
      String _season_1 = match.getSeason();
      _xifexpression_12 = _season_1;
    }
    _builder.append(_xifexpression_12, "               ");
    _builder.append("</b></td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>  ");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<td class=\"FEHER_TRANSPARENT_CR12\" width=\"178\"><b>");
    Object _xifexpression_13 = null;
    int _code = match.getCode();
    boolean _equals_17 = Objects.equal(Integer.valueOf(_code), null);
    if (_equals_17) {
      _xifexpression_13 = "-";
    } else {
      int _code_1 = match.getCode();
      _xifexpression_13 = _code_1;
    }
    _builder.append(_xifexpression_13, "               ");
    _builder.append("</b></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("               ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>  ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateStarters(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\" height=\"15\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Kezd\u0151</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Kezd\u0151</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>                 ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    Team _team1 = match.getTeam1();
    GoalKeeper _goalKeeper = _team1.getGoalKeeper();
    CharSequence _generatePlayer = this.generatePlayer(_goalKeeper);
    _builder.append(_generatePlayer, "         ");
    _builder.newLineIfNotEmpty();
    {
      Team _team1_1 = match.getTeam1();
      EList<Player> _fieldPlayers = _team1_1.getFieldPlayers();
      for(final Player player : _fieldPlayers) {
        _builder.append("         ");
        CharSequence _generatePlayer_1 = this.generatePlayer(player);
        _builder.append(_generatePlayer_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("         ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    Team _team2 = match.getTeam2();
    GoalKeeper _goalKeeper_1 = _team2.getGoalKeeper();
    CharSequence _generatePlayer_2 = this.generatePlayer(_goalKeeper_1);
    _builder.append(_generatePlayer_2, "         ");
    _builder.newLineIfNotEmpty();
    {
      Team _team2_1 = match.getTeam2();
      EList<Player> _fieldPlayers_1 = _team2_1.getFieldPlayers();
      for(final Player player_1 : _fieldPlayers_1) {
        _builder.append("         ");
        CharSequence _generatePlayer_3 = this.generatePlayer(player_1);
        _builder.append(_generatePlayer_3, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("               ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generatePlayer(final Player player) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekos_nez_p01_jegyzokonyv_nez_2(\'148232\');\">          ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>                        ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"20\" height=\"15\">");
    int _squadNumber = player.getSquadNumber();
    _builder.append(_squadNumber, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"269\">");
    String _name = player.getName();
    String _upperCase = _name.toUpperCase();
    _builder.append(_upperCase, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">");
    int _licenceNumber = player.getLicenceNumber();
    _builder.append(_licenceNumber, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSubstitutes(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>    ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\" height=\"15\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Csere</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Csere</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>  ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>                  ");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team1 = match.getTeam1();
      EList<Player> _subtitutePlayers = _team1.getSubtitutePlayers();
      for(final Player substitute : _subtitutePlayers) {
        _builder.append("         ");
        CharSequence _generatePlayer = this.generatePlayer(substitute);
        _builder.append(_generatePlayer, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    {
      Team _team2 = match.getTeam2();
      EList<Player> _subtitutePlayers_1 = _team2.getSubtitutePlayers();
      for(final Player substitute_1 : _subtitutePlayers_1) {
        _builder.append("         ");
        CharSequence _generatePlayer_1 = this.generatePlayer(substitute_1);
        _builder.append(_generatePlayer_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateBench(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"199\"><b>Kispad</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"199\"><b>Kispad</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">                  ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team1 = match.getTeam1();
      EList<Crew> _bench = _team1.getBench();
      for(final Crew crew : _bench) {
        _builder.append("         ");
        CharSequence _generateCrew = this.generateCrew(crew);
        _builder.append(_generateCrew, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team2 = match.getTeam2();
      EList<Crew> _bench_1 = _team2.getBench();
      for(final Crew crew_1 : _bench_1) {
        _builder.append("         ");
        CharSequence _generateCrew_1 = this.generateCrew(crew_1);
        _builder.append(_generateCrew_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("               ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateCrew(final Crew crew) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\">          ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>                        ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"215\" height=\"15\">");
    String _name = crew.getName();
    String _upperCase = _name.toUpperCase();
    _builder.append(_upperCase, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL09\" width=\"84\">");
    CrewRole _role = crew.getRole();
    String _roleToString = GeneratorHelper.roleToString(_role);
    _builder.append(_roleToString, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">");
    int _licenceNumber = crew.getLicenceNumber();
    _builder.append(_licenceNumber, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateScorers(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"20\" height=\"15\">id\u0151</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"165\"><b>G\u00F3ll\u00F6v\u0151</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"20\">id\u0151</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"165\"><b>G\u00F3ll\u00F6v\u0151</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>   ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">                  ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team1 = match.getTeam1();
      Goal[] _goalsOf = GeneratorHelper.goalsOf(_team1);
      for(final Goal goal : _goalsOf) {
        _builder.append("         ");
        CharSequence _generateScorer = this.generateScorer(goal);
        _builder.append(_generateScorer, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("            ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team2 = match.getTeam2();
      Goal[] _goalsOf_1 = GeneratorHelper.goalsOf(_team2);
      for(final Goal goal_1 : _goalsOf_1) {
        _builder.append("         ");
        CharSequence _generateScorer_1 = this.generateScorer(goal_1);
        _builder.append(_generateScorer_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("            ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateScorer(final Goal goal) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekos_nez_p01_jegyzokonyv_nez_2(\'");
    Player _player = goal.getPlayer();
    int _licenceNumber = _player.getLicenceNumber();
    _builder.append(_licenceNumber, "");
    _builder.append("\');\">          ");
    _builder.newLineIfNotEmpty();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>                        ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"ASCR10\" width=\"20\" height=\"15\">");
    int _time = goal.getTime();
    int _minus = (_time - 1);
    int _divide = (_minus / 60);
    _builder.append(_divide, "      ");
    _builder.append("\'</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"265\">");
    _builder.newLine();
    _builder.append("         ");
    Player _player_1 = goal.getPlayer();
    String _name = _player_1.getName();
    String _upperCase = _name.toUpperCase();
    _builder.append(_upperCase, "         ");
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    String _xifexpression = null;
    Team _scorerTeam = goal.getScorerTeam();
    Player _player_2 = goal.getPlayer();
    Team _team = _player_2.getTeam();
    boolean _notEquals = (!Objects.equal(_scorerTeam, _team));
    if (_notEquals) {
      _xifexpression = "(\u00F6ng\u00F3l)";
    }
    _builder.append(_xifexpression, "         ");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("</td>     ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">");
    Player _player_3 = goal.getPlayer();
    int _licenceNumber_1 = _player_3.getLicenceNumber();
    _builder.append(_licenceNumber_1, "      ");
    _builder.append("</td> ");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateFaults(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"20\" height=\"15\">id\u0151</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"115\"><b>S\u00E1rga-Piros lap</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"49\">lap</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"20\">id\u0151</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"115\"><b>S\u00E1rga-Piros lap</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"49\">lap</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">                  ");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team1 = match.getTeam1();
      Fault[] _faultsOf = GeneratorHelper.faultsOf(_team1);
      for(final Fault fault : _faultsOf) {
        _builder.append("         ");
        CharSequence _generateFault = this.generateFault(fault);
        _builder.append(_generateFault, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team2 = match.getTeam2();
      Fault[] _faultsOf_1 = GeneratorHelper.faultsOf(_team2);
      for(final Fault fault_1 : _faultsOf_1) {
        _builder.append("         ");
        CharSequence _generateFault_1 = this.generateFault(fault_1);
        _builder.append(_generateFault_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("            ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateFault(final Fault fault) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekos_nez_p01_jegyzokonyv_nez_2(\'");
    Player _player = fault.getPlayer();
    int _licenceNumber = _player.getLicenceNumber();
    _builder.append(_licenceNumber, "");
    _builder.append("\');\">          ");
    _builder.newLineIfNotEmpty();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"20\" height=\"15\">");
    int _time = fault.getTime();
    int _minus = (_time - 1);
    int _divide = (_minus / 60);
    _builder.append(_divide, "      ");
    _builder.append("\'</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"215\">");
    Player _player_1 = fault.getPlayer();
    String _name = _player_1.getName();
    String _upperCase = _name.toUpperCase();
    _builder.append(_upperCase, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=");
    FaultType _type = fault.getType();
    String _faultToClass = this.faultToClass(_type);
    _builder.append(_faultToClass, "      ");
    _builder.append(" width=\"49\">");
    FaultType _type_1 = fault.getType();
    String _faultToString = GeneratorHelper.faultToString(_type_1);
    _builder.append(_faultToString, "      ");
    _builder.append("</td>                    ");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">");
    Player _player_2 = fault.getPlayer();
    int _licenceNumber_1 = _player_2.getLicenceNumber();
    _builder.append(_licenceNumber_1, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public String faultToClass(final FaultType type) {
    boolean _equals = Objects.equal(type, FaultType.YELLOW_CARD);
    if (_equals) {
      return "HACC09";
    }
    boolean _equals_1 = Objects.equal(type, FaultType.RED_CARD);
    if (_equals_1) {
      return "GACC09";
    }
    return "\"FEKETE_TRANSPARENT_CL09\"";
  }
  
  public CharSequence generateSubstitutions(final Match match) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_BARNA\" width=\"720\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table>    ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\" height=\"15\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Csere</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR09\" width=\"20\">mez</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"100\">n\u00E9v <i>(id\u0151)</i></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"BARNA_TRANSPARENT_CL11\" width=\"169\"><b>Csere</b></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR10\" width=\"50\">igazol\u00E1s</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>         ");
    _builder.newLine();
    _builder.append("</table>  ");
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>                  ");
    _builder.newLine();
    _builder.newLine();
    {
      Team _team1 = match.getTeam1();
      Substitution[] _substitutionsOf = GeneratorHelper.substitutionsOf(_team1);
      for(final Substitution substitution : _substitutionsOf) {
        _builder.append("         ");
        CharSequence _generateSubstitution = this.generateSubstitution(substitution);
        _builder.append(_generateSubstitution, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"9\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_BARNA\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"10\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"350\" valign=\"top\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    {
      Team _team2 = match.getTeam2();
      Substitution[] _substitutionsOf_1 = GeneratorHelper.substitutionsOf(_team2);
      for(final Substitution substitution_1 : _substitutionsOf_1) {
        _builder.append("         ");
        CharSequence _generateSubstitution_1 = this.generateSubstitution(substitution_1);
        _builder.append(_generateSubstitution_1, "         ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("   ");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</tr>            ");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSubstitution(final Substitution substitution) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekos_nez_p01_jegyzokonyv_nez_2(\'");
    Player _substitute = substitution.getSubstitute();
    int _licenceNumber = _substitute.getLicenceNumber();
    _builder.append(_licenceNumber, "");
    _builder.append("\');\">          ");
    _builder.newLineIfNotEmpty();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"20\" height=\"15\">");
    Player _substitute_1 = substitution.getSubstitute();
    int _squadNumber = _substitute_1.getSquadNumber();
    _builder.append(_squadNumber, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"269\">");
    Player _substitute_2 = substitution.getSubstitute();
    String _name = _substitute_2.getName();
    String _upperCase = _name.toUpperCase();
    _builder.append(_upperCase, "      ");
    _builder.append(" </td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\">");
    Player _substitute_3 = substitution.getSubstitute();
    int _licenceNumber_1 = _substitute_3.getLicenceNumber();
    _builder.append(_licenceNumber_1, "      ");
    _builder.append("</td>");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<div class=\"MOff\" style=\"cursor: pointer; width: 350;\" onMouseOut=\"this.className=\'MOff\';\" onmouseover=\"this.className=\'MOn_1\';\" OnClick=\"jatekos_nez_p01_jegyzokonyv_nez_2(\'");
    Player _instead = substitution.getInstead();
    int _licenceNumber_2 = _instead.getLicenceNumber();
    _builder.append(_licenceNumber_2, "");
    _builder.append("\');\">                   ");
    _builder.newLineIfNotEmpty();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"20\" height=\"15\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"4\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td width=\"5\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL11\" width=\"50\"><i>");
    int _time = substitution.getTime();
    int _minus = (_time - 1);
    int _divide = (_minus / 60);
    _builder.append(_divide, "      ");
    _builder.append("\'</i></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CL10\" width=\"219\"><i>");
    Player _instead_1 = substitution.getInstead();
    String _name_1 = _instead_1.getName();
    String _upperCase_1 = _name_1.toUpperCase();
    _builder.append(_upperCase_1, "      ");
    _builder.append(" helyett</i></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<td class=\"URES_SZURKE\" width=\"1\"></td>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<td class=\"FEKETE_TRANSPARENT_CR11\" width=\"50\"><i>");
    Player _instead_2 = substitution.getInstead();
    int _licenceNumber_3 = _instead_2.getLicenceNumber();
    _builder.append(_licenceNumber_3, "      ");
    _builder.append("</i></td>");
    _builder.newLineIfNotEmpty();
    _builder.append("   ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\">");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<tr><td class=\"URES_SZURKE\" width=\"350\" height=\"1\"></td></tr>");
    _builder.newLine();
    _builder.append("</table> ");
    _builder.newLine();
    return _builder;
  }
}
