package hu.bme.mit.inf.mvsd;

import hu.bme.mit.inf.mvsd.allplayers.AllPlayersMatcher;
import hu.bme.mit.inf.mvsd.betweeninsubs.BetweenInSubsMatcher;
import hu.bme.mit.inf.mvsd.betweenoutsubs.BetweenOutSubsMatcher;
import hu.bme.mit.inf.mvsd.captainisinotherteam.CaptainIsInOtherTeamMatcher;
import hu.bme.mit.inf.mvsd.decreasingeventtime.DecreasingEventTimeMatcher;
import hu.bme.mit.inf.mvsd.duplicatesubstitution.DuplicateSubstitutionMatcher;
import hu.bme.mit.inf.mvsd.eventafterfullgametime.EventAfterFullGameTimeMatcher;
import hu.bme.mit.inf.mvsd.eventaftergametimeifequalininitialtime.EventAfterGameTimeIfEqualInInitialTimeMatcher;
import hu.bme.mit.inf.mvsd.fieldplayers.FieldPlayersMatcher;
import hu.bme.mit.inf.mvsd.inoutinsubs.InOutInSubsMatcher;
import hu.bme.mit.inf.mvsd.insubs.InSubsMatcher;
import hu.bme.mit.inf.mvsd.insubsafterlastoutsubs.InSubsAfterLastOutSubsMatcher;
import hu.bme.mit.inf.mvsd.insubsaftersubs.InSubsAfterSubsMatcher;
import hu.bme.mit.inf.mvsd.invalidsubscandidate.InvalidSubsCandidateMatcher;
import hu.bme.mit.inf.mvsd.lastinsubs.LastInSubsMatcher;
import hu.bme.mit.inf.mvsd.lastoutsubs.LastOutSubsMatcher;
import hu.bme.mit.inf.mvsd.matchteamsubjectinconsistency.MatchTeamSubjectInconsistencyMatcher;
import hu.bme.mit.inf.mvsd.outinoutsubs.OutInOutSubsMatcher;
import hu.bme.mit.inf.mvsd.outsubs.OutSubsMatcher;
import hu.bme.mit.inf.mvsd.outsubsafterlastinsubs.OutSubsAfterLastInSubsMatcher;
import hu.bme.mit.inf.mvsd.outsubsaftersubs.OutSubsAfterSubsMatcher;
import hu.bme.mit.inf.mvsd.playerscoresafterredcard.PlayerScoresAfterRedCardMatcher;
import hu.bme.mit.inf.mvsd.playersubstitutesafterredcard.PlayerSubstitutesAfterRedCardMatcher;
import hu.bme.mit.inf.mvsd.subs.SubsMatcher;
import hu.bme.mit.inf.mvsd.teamfaultcountfirsthalf.TeamFaultCountFirstHalfMatcher;
import hu.bme.mit.inf.mvsd.teamfaultcountsecondhalf.TeamFaultCountSecondHalfMatcher;
import hu.bme.mit.inf.mvsd.teamfaults.TeamFaultsMatcher;
import hu.bme.mit.inf.mvsd.teamfaultsfirsthalf.TeamFaultsFirstHalfMatcher;
import hu.bme.mit.inf.mvsd.teamfaultssecondhalf.TeamFaultsSecondHalfMatcher;
import hu.bme.mit.inf.mvsd.teamgoalcount.TeamGoalCountMatcher;
import hu.bme.mit.inf.mvsd.teamgoalcounthalftime.TeamGoalCountHalftimeMatcher;
import hu.bme.mit.inf.mvsd.teamgoalcountinitialtime.TeamGoalCountInitialTimeMatcher;
import hu.bme.mit.inf.mvsd.teamgoals.TeamGoalsMatcher;
import hu.bme.mit.inf.mvsd.teamgoalshalftime.TeamGoalsHalfTimeMatcher;
import hu.bme.mit.inf.mvsd.teamgoalsinitialtime.TeamGoalsInitialTimeMatcher;
import hu.bme.mit.inf.mvsd.teammembernotincontainingteam.TeamMemberNotInContainingTeamMatcher;
import hu.bme.mit.inf.mvsd.teamsubstitutioncount.TeamSubstitutionCountMatcher;
import hu.bme.mit.inf.mvsd.teamsubstitutions.TeamSubstitutionsMatcher;
import hu.bme.mit.inf.mvsd.teamtimeouts.TeamTimeoutsMatcher;
import hu.bme.mit.inf.mvsd.teamtimeoutsfirsthalf.TeamTimeoutsFirstHalfMatcher;
import hu.bme.mit.inf.mvsd.teamtimeoutssecondhalf.TeamTimeoutsSecondHalfMatcher;
import org.eclipse.incquery.runtime.api.impl.BaseGeneratedPatternGroup;
import org.eclipse.incquery.runtime.exception.IncQueryException;

public final class GroupOfFileQueries extends BaseGeneratedPatternGroup {
  public GroupOfFileQueries() throws IncQueryException {
    matcherFactories.add(TeamFaultsMatcher.factory());
    matcherFactories.add(CaptainIsInOtherTeamMatcher.factory());
    matcherFactories.add(DuplicateSubstitutionMatcher.factory());
    matcherFactories.add(TeamFaultsSecondHalfMatcher.factory());
    matcherFactories.add(PlayerScoresAfterRedCardMatcher.factory());
    matcherFactories.add(OutInOutSubsMatcher.factory());
    matcherFactories.add(EventAfterFullGameTimeMatcher.factory());
    matcherFactories.add(TeamGoalCountInitialTimeMatcher.factory());
    matcherFactories.add(InSubsMatcher.factory());
    matcherFactories.add(TeamTimeoutsSecondHalfMatcher.factory());
    matcherFactories.add(TeamMemberNotInContainingTeamMatcher.factory());
    matcherFactories.add(EventAfterGameTimeIfEqualInInitialTimeMatcher.factory());
    matcherFactories.add(InvalidSubsCandidateMatcher.factory());
    matcherFactories.add(AllPlayersMatcher.factory());
    matcherFactories.add(OutSubsMatcher.factory());
    matcherFactories.add(TeamTimeoutsMatcher.factory());
    matcherFactories.add(SubsMatcher.factory());
    matcherFactories.add(LastInSubsMatcher.factory());
    matcherFactories.add(BetweenOutSubsMatcher.factory());
    matcherFactories.add(BetweenInSubsMatcher.factory());
    matcherFactories.add(TeamGoalCountMatcher.factory());
    matcherFactories.add(TeamSubstitutionCountMatcher.factory());
    matcherFactories.add(TeamSubstitutionsMatcher.factory());
    matcherFactories.add(TeamGoalsMatcher.factory());
    matcherFactories.add(InSubsAfterLastOutSubsMatcher.factory());
    matcherFactories.add(InSubsAfterSubsMatcher.factory());
    matcherFactories.add(TeamFaultCountSecondHalfMatcher.factory());
    matcherFactories.add(MatchTeamSubjectInconsistencyMatcher.factory());
    matcherFactories.add(FieldPlayersMatcher.factory());
    matcherFactories.add(TeamGoalCountHalftimeMatcher.factory());
    matcherFactories.add(TeamFaultsFirstHalfMatcher.factory());
    matcherFactories.add(LastOutSubsMatcher.factory());
    matcherFactories.add(DecreasingEventTimeMatcher.factory());
    matcherFactories.add(PlayerSubstitutesAfterRedCardMatcher.factory());
    matcherFactories.add(TeamGoalsInitialTimeMatcher.factory());
    matcherFactories.add(InOutInSubsMatcher.factory());
    matcherFactories.add(OutSubsAfterLastInSubsMatcher.factory());
    matcherFactories.add(TeamTimeoutsFirstHalfMatcher.factory());
    matcherFactories.add(OutSubsAfterSubsMatcher.factory());
    matcherFactories.add(TeamFaultCountFirstHalfMatcher.factory());
    matcherFactories.add(TeamGoalsHalfTimeMatcher.factory());
    
  }
}
